''''CÓDIGOS MAIS UTILIZADOS lSPA'''
import csv
import string

class Codigos():

    def __init__(self):

      self.ufnome={"Brasil":"00",
               "Rondônia":"11",
               "Acre":"12",
               "Amazonas":"13",
               "Roraima":"14",
               "Pará":"15",
               "Amapá":"16",
               "Tocantins":"17",
               "Maranhão":"21",
               "Piauí":"22",
               "Ceará":"23",
               "Rio Grande do Norte":"24",
               "Paraíba":"25",
               "Pernambuco":"26",
               "Alagoas":"27",
               "Sergipe":"28",
               "Bahia":"29",
               "Minas Gerais":"31",
               "Espírito Santo":"32",
               "Rio de Janeiro":"33",
               "São Paulo":"35",
               "Paraná":"41",
               "Santa Catarina":"42",
               "Rio Grande do Sul":"43",
               "Mato Grosso do Sul":"50",
               "Mato Grosso":"51",
               "Goiás":"52",
               "Distrito Federal":"53",
               }
      self.ufcodigo={"00":"Brasil",
               "11":"Rondônia",
               "12":"Acre",
               "13":"Amazonas",
               "14":"Roraima",
               "15":"Pará",
               "16":"Amapá",
               "17":"Tocantins",
               "21":"Maranhão",
               "22":"Piauí",
               "23":"Ceará",
               "24":"Rio Grande do Norte",
               "25":"Paraíba",
               "26":"Pernambuco",
               "27":"Alagoas",
               "28":"Sergipe",
               "29":"Bahia",
               "31":"Minas Gerais",
               "32":"Espírito Santo",
               "33":"Rio de Janeiro",
               "35":"São Paulo",
               "41":"Paraná",
               "42":"Santa Catarina",
               "43":"Rio Grande do Sul",
               "50":"Mato Grosso do Sul",
               "51":"Mato Grosso",
               "52":"Goiás",
               "53":"Distrito Federal",
               }
 
      self.ufsigla={"00":"BR",
               "11":"RO",
               "12":"AC",
               "13":"AM",
               "14":"RR",
               "15":"PA",
               "16":"AP",
               "17":"TO",
               "21":"MA",
               "22":"PI",
               "23":"CE",
               "24":"RN",
               "25":"PB",
               "26":"PE",
               "27":"AL",
               "28":"SE",
               "29":"BA",
               "31":"MG",
               "32":"ES",
               "33":"RJ",
               "35":"SP",
               "41":"PR",
               "42":"SC",
               "43":"RS",
               "50":"MS",
               "51":"MT",
               "52":"GO",
               "53":"DF",
               }
      self.regnome={"Sul":"4",
                "Norte":"1",
                "Centro-Oeste":"5",
                "Sudeste":"3",
                "Nordeste":"2",
                "Brasil":"0"}
      self.regcodigo={"4":"Sul",
                "1":"Norte",
                "5":"Centro-Oeste",
                "3":"Sudeste",
                "2":"Nordeste",
                "0":"Brasil"}

	


    
        
